import { Inter } from 'next/font/google';
import '@/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'My Note app',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="flex justify-center bg-indigo-200">
      <body className={inter.className}>
        <div className="mt-20 bg-indigo-200">{children}</div>
      </body>
    </html>
  );
}
